services:
  db:
    image: postgres:17
    container_name: db_agenda
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - private
  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
      - static:/static
    depends_on:
      - db
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DEBUG: ${DEBUG}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
    networks:
      - private
      - public
  nginx:
    build: ./nginx
    ports:
      - "81:80"
    depends_on:
      - web
    networks:
      - public
    volumes:
      - static:/static

volumes:
  postgres_db:
  static:

networks:
  private:
    driver: bridge
  public:
    driver: bridge